[FIX] account_banking_payment_transfer: Don't fail when no transfer move
If you make a payment order with a payment mode without transfer settings,
the test for moving the workflow to done fails with the error:

```
  File "/opt/odoo/auto/addons/account_banking_payment_transfer/model/account_payment.py", line 115, in test_done
    (tuple(self.get_transfer_move_line_ids()),)
  File "/opt/odoo/custom/src/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "syntax error at or near ")"
LINE 2:             where id in () and reconcile_id is null
                                 ^
" while evaluating
u'test_done()'
```