FIX account_banking_payment_transfer
Steps:

 - Install account_banking_payment_transfer
 - Create supplier invoice
 - Create payment order
 - Import the supplier invoice
 - Confirm
 - 'Make Payments'

Get

  File "parts/odoo/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ValueError: "syntax error at or near ")"
LINE 2:             where id in () and reconcile_id is null
                                 ^
" while evaluating
u'test_done()'